//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Translations {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Translations.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a new car model.
        /// </summary>
        public static string AddCarString {
            get {
                return ResourceManager.GetString("AddCarString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a maintenance.
        /// </summary>
        public static string AddMaintenanceString {
            get {
                return ResourceManager.GetString("AddMaintenanceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string AddString {
            get {
                return ResourceManager.GetString("AddString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a vehicle.
        /// </summary>
        public static string AddVehicleString {
            get {
                return ResourceManager.GetString("AddVehicleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string BackString {
            get {
                return ResourceManager.GetString("BackString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brand:.
        /// </summary>
        public static string BrandString {
            get {
                return ResourceManager.GetString("BrandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Car model name should not be empty.
        /// </summary>
        public static string CarNameEmptyString {
            get {
                return ResourceManager.GetString("CarNameEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The car model name should at least be 1 character long.
        /// </summary>
        public static string CarNameNotEmptyString {
            get {
                return ResourceManager.GetString("CarNameNotEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Car model name .
        /// </summary>
        public static string CarNameString {
            get {
                return ResourceManager.GetString("CarNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cars model.
        /// </summary>
        public static string CarsString {
            get {
                return ResourceManager.GetString("CarsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Carmodel:.
        /// </summary>
        public static string CarString {
            get {
                return ResourceManager.GetString("CarString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        public static string ConfirmString {
            get {
                return ResourceManager.GetString("ConfirmString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while deleting the car model.
        /// </summary>
        public static string DeleteErrorCar {
            get {
                return ResourceManager.GetString("DeleteErrorCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The maintenance description should at least be 1 character long.
        /// </summary>
        public static string DescriptionEmptyString {
            get {
                return ResourceManager.GetString("DescriptionEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description:.
        /// </summary>
        public static string DescriptionString {
            get {
                return ResourceManager.GetString("DescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Energy.
        /// </summary>
        public static string EnergyString {
            get {
                return ResourceManager.GetString("EnergyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A Car model already exist for this brand.
        /// </summary>
        public static string ExistingCarNameForBrandString {
            get {
                return ResourceManager.GetString("ExistingCarNameForBrandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A vehicle for this registration number already exists.
        /// </summary>
        public static string ExistingRegisterString {
            get {
                return ResourceManager.GetString("ExistingRegisterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frequency maintenance:.
        /// </summary>
        public static string FrequencyMaintenanceString {
            get {
                return ResourceManager.GetString("FrequencyMaintenanceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string HomeString {
            get {
                return ResourceManager.GetString("HomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while loading vehicles.
        /// </summary>
        public static string LoadErrorVehicles {
            get {
                return ResourceManager.GetString("LoadErrorVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        public static string LoadingString {
            get {
                return ResourceManager.GetString("LoadingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maintenance frequency.
        /// </summary>
        public static string MaintenanceFrequencyString {
            get {
                return ResourceManager.GetString("MaintenanceFrequencyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mileage should be a positive.
        /// </summary>
        public static string MileagePositiveString {
            get {
                return ResourceManager.GetString("MileagePositiveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mileage:.
        /// </summary>
        public static string MileageString {
            get {
                return ResourceManager.GetString("MileageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name: .
        /// </summary>
        public static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The frequency maintenance cannot be negative.
        /// </summary>
        public static string NegativeFrequencyMaintenanceString {
            get {
                return ResourceManager.GetString("NegativeFrequencyMaintenanceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No cars models to display.
        /// </summary>
        public static string NoCarDisplayString {
            get {
                return ResourceManager.GetString("NoCarDisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Vehicles late for maintenances.
        /// </summary>
        public static string NoVehicleLateForMaintenanceString {
            get {
                return ResourceManager.GetString("NoVehicleLateForMaintenanceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No vehicles to display.
        /// </summary>
        public static string NoVehiclesDisplayString {
            get {
                return ResourceManager.GetString("NoVehiclesDisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mileage should be positive.
        /// </summary>
        public static string PositiveMileageString {
            get {
                return ResourceManager.GetString("PositiveMileageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registration number:.
        /// </summary>
        public static string RegisterNumberString {
            get {
                return ResourceManager.GetString("RegisterNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The registration number shoud be between 7 and 9 characters long.
        /// </summary>
        public static string RegistrationNumberFormatString {
            get {
                return ResourceManager.GetString("RegistrationNumberFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save changes.
        /// </summary>
        public static string SaveModificationsString {
            get {
                return ResourceManager.GetString("SaveModificationsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a brand.
        /// </summary>
        public static string SelectBrandString {
            get {
                return ResourceManager.GetString("SelectBrandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a car model.
        /// </summary>
        public static string SelectCarString {
            get {
                return ResourceManager.GetString("SelectCarString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have to select a brand.
        /// </summary>
        public static string ShouldSelectBrandString {
            get {
                return ResourceManager.GetString("ShouldSelectBrandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have to select a car.
        /// </summary>
        public static string ShouldSelectCarString {
            get {
                return ResourceManager.GetString("ShouldSelectCarString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vehicles late for maintenances.
        /// </summary>
        public static string VehicleLateForMaintenanceString {
            get {
                return ResourceManager.GetString("VehicleLateForMaintenanceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vehicles.
        /// </summary>
        public static string VehiclesString {
            get {
                return ResourceManager.GetString("VehiclesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vehicle.
        /// </summary>
        public static string VehicleString {
            get {
                return ResourceManager.GetString("VehicleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The year of the vehicle should be between 1900 and.
        /// </summary>
        public static string VehicleYearString {
            get {
                return ResourceManager.GetString("VehicleYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Year:.
        /// </summary>
        public static string YearString {
            get {
                return ResourceManager.GetString("YearString", resourceCulture);
            }
        }
    }
}
